
const compra=[
    {
        idCompra:1,
        idUsuario:3,
        idDireccion:1,
        idEstadoPago:0,
        fechaCompra:"",
        ts_create:"",
        ts_update:"",
    },
    {
        idCompra:2,
        idUsuario:2,
        idDireccion:3,
        idEstadoPago:1,
        fechaCompra:"",
        ts_create:"",
        ts_update:"",
    },
    {
        idCompra:3,
        idUsuario:1,
        idDireccion:4,
        idEstadoPago:0,
        fechaCompra:"",
        ts_create:"",
        ts_update:"",
    },
    {
        idCompra:4,
        idUsuario:5,
        idDireccion:5,
        idEstadoPago:1,
        fechaCompra:"",
        ts_create:"",
        ts_update:"",
    },
    {
        idCompra:5,
        idUsuario:4,
        idDireccion:4,
        idEstadoPago:1,
        fechaCompra:"",
        ts_create:"",
        ts_update:"",
    }
]

module.exports = compra;